*** Factors Affecting Book Success ***

The Basics

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../data/Books_Data_Clean.csv')
dfCleaning = df.copy()

Explore The Data

In [3]:
df.head(10)

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
0,0,1975.0,Beowulf,"Unknown, Seamus Heaney",en-US,Novice,3.42,155903,genre fiction,34160.00,20496.000,4.88,1,HarperCollins Publishers,7000
1,1,1987.0,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,Intermediate,4.23,145267,genre fiction,12437.50,7462.500,1.99,2,HarperCollins Publishers,6250
2,2,2015.0,Go Set a Watchman,Harper Lee,eng,Novice,3.31,138669,genre fiction,47795.00,28677.000,8.69,3,"Amazon Digital Services, Inc.",5500
3,3,2008.0,When You Are Engulfed in Flames,David Sedaris,en-US,Intermediate,4.04,150898,fiction,41250.00,24750.000,7.50,3,Hachette Book Group,5500
4,4,2011.0,Daughter of Smoke & Bone,Laini Taylor,eng,Intermediate,4.04,198283,genre fiction,37952.50,22771.500,7.99,4,Penguin Group (USA) LLC,4750
5,5,2015.0,Red Queen,Victoria Aveyard,eng,Intermediate,4.08,83354,genre fiction,19960.00,0.000,4.99,5,"Amazon Digital Services, Inc.",4000
6,6,2011.0,The Power of Habit,Charles Duhigg,eng,Intermediate,4.03,155977,genre fiction,27491.67,16495.002,6.99,6,HarperCollins Publishers,3933
7,7,1994.0,Midnight in the Garden of Good and Evil,John Berendt,eng,Intermediate,3.90,167997,nonfiction,26182.00,15709.200,6.89,8,Hachette Book Group,3800
8,8,2012.0,Hopeless,Colleen Hoover,eng,Intermediate,4.34,189938,genre fiction,26093.67,15656.202,6.99,9,HarperCollins Publishers,3733
9,9,1905.0,A Little Princess,"Frances Hodgson Burnett, Nancy Bond",eng,Intermediate,4.20,199872,genre fiction,23792.34,14275.404,6.49,10,Random House LLC,3666

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index                1070 non-null   int64
 1   Publishing Year      1069 non-null   float64
 2   Book Name            1047 non-null   str
 3   Author               1070 non-null   str
 4   language_code        1017 non-null   str
 5   Author_Rating        1070 non-null   str
 6   Book_average_rating  1070 non-null   float64
 7   Book_ratings_count   1070 non-null   int64
 8   genre                1070 non-null   str
 9   gross sales          1070 non-null   float64
 10  publisher revenue    1070 non-null   float64
 11  sale price           1070 non-null   float64
 12  sales rank           1070 non-null   int64
 13  Publisher            1070 non-null   str
 14  units sold           1070 non-null   int64
dtypes: float64(5), int64(4), str(6)
memory usage: 125.5 KB

1) Publishing Year, Book Name,And Language_code has null values
2) columns Titles in inconsistence format, some use space and some use under_score
3) datatype of Publishing Year is float while it should be date

In [5]:
match_index = df['index'] == df.index
match_index[match_index == True].count()

np.int64(1070)

i discover that index column and indexRange are the same

In [6]:
df.describe()

,index,Publishing Year,Book_average_rating,Book_ratings_count,gross sales,publisher revenue,sale price,sales rank,units sold
count,1070.000000,1069.000000,1070.000000,1070.000000,1070.000000,1070.000000,1070.000000,1070.000000,1070.000000
mean,534.500000,1971.377923,4.007000,94909.913084,1856.622944,843.281030,4.869561,611.652336,9676.980374
std,309.026698,185.080257,0.247244,31513.242518,3936.924240,2257.596743,3.559919,369.849830,15370.571306
min,0.000000,-560.000000,2.970000,27308.000000,104.940000,0.000000,0.990000,1.000000,106.000000
25%,267.250000,1985.000000,3.850000,70398.000000,372.465000,0.000000,1.990000,287.500000,551.250000
50%,534.500000,2003.000000,4.015000,89309.000000,809.745000,273.078000,3.990000,595.500000,3924.000000
75%,801.750000,2010.000000,4.170000,113906.500000,1487.957500,721.180500,6.990000,932.500000,5312.250000
max,1069.000000,2016.000000,4.770000,206792.000000,47795.000000,28677.000000,33.860000,1273.000000,61560.000000

In [7]:
def detect_outliers(value, upper, lower):
    if value >= upper:
        return 'upper'
    elif value <= lower:
        return 'lower'
    return 'normal'
    
outliers = pd.DataFrame(index=df.index)

In [8]:
# Book_ratings_cuont
ratingCount_Q1 = df['Book_ratings_count'].quantile(0.25)
ratingCount_Q3 = df['Book_ratings_count'].quantile(0.75)

IQR = ratingCount_Q3 - ratingCount_Q1

upper = ratingCount_Q3 + (1.5 * IQR)
lower = ratingCount_Q1 - (1.5 * IQR) 


outliers["book_ratings_count"] = df["Book_ratings_count"].apply(lambda value: detect_outliers(value, upper, lower))

In [9]:
# gross sales
grossSales_Q1 = df['gross sales'].quantile(0.25)
grossSales_Q3 = df['gross sales'].quantile(0.75)

IQR = grossSales_Q3 - grossSales_Q1

upper = grossSales_Q3 + (1.5 * IQR)
lower = grossSales_Q1 - (1.5 * IQR)

outliers["gross_sales"] = df["gross sales"].apply(lambda value: detect_outliers(value, upper, lower))

In [10]:
# units sold
uniteSold_Q1 = df['units sold'].quantile(0.25)
uniteSold_Q3 = df['units sold'].quantile(0.75)

IQR = uniteSold_Q3 - uniteSold_Q1

upper = uniteSold_Q3 + (1.5 * IQR)
lower = uniteSold_Q1 - (1.5 * IQR) 

outliers["units_sold"] = df["units sold"].apply(lambda value: detect_outliers(value, upper, lower))

In [11]:
outliers["book_ratings_count"].unique()

<StringArray>
['normal', 'upper']
Length: 2, dtype: str

i test the unique valus for all theree columns, and discovered that, all values  
either normal or upper there are no lower values

In [12]:
outliers.loc[outliers['book_ratings_count'] == 'upper', ['book_ratings_count']].count()

book_ratings_count    13
dtype: int64

In [13]:
outliers.loc[outliers['gross_sales'] == 'upper', ['gross_sales']].count()

gross_sales    129
dtype: int64

In [14]:
outliers.loc[outliers['units_sold'] == 'upper', ['units_sold']].count()

units_sold    204
dtype: int64

outliers quantity is relatively logical

In [15]:
df[df.duplicated(keep='first') == True]

Empty DataFrame
Columns: [index, Publishing Year, Book Name, Author, language_code, Author_Rating, Book_average_rating, Book_ratings_count, genre, gross sales, publisher revenue, sale price, sales rank, Publisher , units sold]
Index: []

there are no duplicates (before cleaning and standardize the format)

In [16]:
df[df['Publishing Year'] <= 1200]

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
241,241,-380.0,Î Î¿Î»Î¹Ï„ÎµÎ¯Î±,"Plato, Desmond Lee",eng,Intermediate,3.90,110274,genre fiction,387.09,232.254,0.99,265,"Amazon Digital Services, Inc.",391
293,293,-430.0,ÎŸá¼°Î´Î¯Ï€Î¿Ï…Ï‚ Î¤ÏÏÎ±Î½Î½Î¿Ï‚,"Sophocles, J.E. Thomas",eng,Intermediate,3.67,119496,genre fiction,2460.92,1476.552,7.99,315,Hachette Book Group,308
568,568,-300.0,é“å¾·ç¶“ [dÃ o dÃ© jÄ«ng],"Lao Tzu, Gia-Fu Feng, Jane English, Chungliang...",eng,Excellent,4.31,39863,genre fiction,665.55,399.330,4.59,632,Penguin Group (USA) LLC,3915
589,589,-560.0,Aesopica,"Aesop, Laura Harris, Laura Gibbs",eng,Excellent,4.05,88508,genre fiction,693.61,0.000,4.99,663,"Amazon Digital Services, Inc.",53784
749,749,-17.0,Ã†neis,"Virgil, Robert Fitzgerald",eng,Intermediate,3.81,75051,genre fiction,114.84,0.000,0.99,863,"Amazon Digital Services, Inc.",31752
990,990,-441.0,á¼ˆÎ½Ï„Î¹Î³ÏŒÎ½Î·,"Sophocles, J.E. Thomas",eng,Intermediate,3.60,67608,genre fiction,106.92,64.152,0.99,1167,"Amazon Digital Services, Inc.",108

there are negative values in Publishing Year, and that is a data entry error

some books names contain encodeing errors, some values might be fixed

In [17]:
df['language_code'].unique()

<StringArray>
['en-US', 'eng', nan, 'spa', 'en-GB', 'fre', 'en-CA', 'nl', 'ara']
Length: 9, dtype: str

english language has more then dialect plus the general eng

In [18]:
df['Author_Rating'].unique()

<StringArray>
['Novice', 'Intermediate', 'Famous', 'Excellent']
Length: 4, dtype: str

In [19]:
df['genre'].unique()

<StringArray>
['genre fiction', 'fiction', 'nonfiction', 'children']
Length: 4, dtype: str

In [20]:
df['Publisher '].unique()

<StringArray>
[            'HarperCollins Publishers',
       'Amazon Digital Services,  Inc.',
                  'Hachette Book Group',
              'Penguin Group (USA) LLC',
                     'Random House LLC',
 'Simon and Schuster Digital Sales Inc',
                            'Macmillan',
             'HarperCollins Publishing',
   'HarperCollins Christian Publishing']
Length: 9, dtype: str

HarperCollins are repeated three times in different format  
publisher column title has a space at the end, i have to check on other titles as well

In [21]:
df['Author'].sort_values()

1014                      A.A. Milne, Ernest H. Shepard
775                                     A.S.A. Harrison
764                                         Abbi Glines
281                                         Abbi Glines
931                                        Adam Johnson
                             ...
904                                      William Styron
821                            Yana Toboso, Tomo Kimura
474                                         Zadie Smith
944     Ø£Ø­Ù„Ø§Ù… Ù…Ø³ØªØºØ§Ù†Ù…ÙŠ, Ahlam Mosteghanemi
841                                   Ø£Ø­Ù…Ø¯ Ù…Ø±Ø§Ø¯
Name: Author, Length: 1070, dtype: str

there are encoding issuse in Author column also, but it's not related with analyzing main focus

Clean The Data

In [22]:
dfCleaning = dfCleaning.drop('index', axis=1)

In [23]:
dfCleaning.head()

,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
0,1975.0,Beowulf,"Unknown, Seamus Heaney",en-US,Novice,3.42,155903,genre fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1987.0,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,Intermediate,4.23,145267,genre fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2015.0,Go Set a Watchman,Harper Lee,eng,Novice,3.31,138669,genre fiction,47795.0,28677.0,8.69,3,"Amazon Digital Services, Inc.",5500
3,2008.0,When You Are Engulfed in Flames,David Sedaris,en-US,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,2011.0,Daughter of Smoke & Bone,Laini Taylor,eng,Intermediate,4.04,198283,genre fiction,37952.5,22771.5,7.99,4,Penguin Group (USA) LLC,4750

In [24]:
dfCleaning.rename(columns={
    'Publishing Year':'publishing_year',
    'Book Name':'book_name',
    'Author':'author',
    'Author_Rating':'author_rating',
    'Book_average_rating':'book_avarage_rating',
    'Book_ratings_count':'book_ratings_count',
    'gross sales':'gross_sales',
    'publisher revenue':'publisher_revenue',
    'sale price':'sale_price',
    'sales rank':'sales_rank',
    'Publisher ':'publisher',
    'units sold':'units_sold',
    }, inplace=True)

In [25]:
dfCleaning.head()

,publishing_year,book_name,author,language_code,author_rating,book_avarage_rating,book_ratings_count,genre,gross_sales,publisher_revenue,sale_price,sales_rank,publisher,units_sold
0,1975.0,Beowulf,"Unknown, Seamus Heaney",en-US,Novice,3.42,155903,genre fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1987.0,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,Intermediate,4.23,145267,genre fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2015.0,Go Set a Watchman,Harper Lee,eng,Novice,3.31,138669,genre fiction,47795.0,28677.0,8.69,3,"Amazon Digital Services, Inc.",5500
3,2008.0,When You Are Engulfed in Flames,David Sedaris,en-US,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,2011.0,Daughter of Smoke & Bone,Laini Taylor,eng,Intermediate,4.04,198283,genre fiction,37952.5,22771.5,7.99,4,Penguin Group (USA) LLC,4750

In [26]:
dfCleaning.loc[dfCleaning['publishing_year'] <= 0, 'publishing_year'] = None

In [27]:
dfCleaning[dfCleaning['publishing_year'] <= 0]

Empty DataFrame
Columns: [publishing_year, book_name, author, language_code, author_rating, book_avarage_rating, book_ratings_count, genre, gross_sales, publisher_revenue, sale_price, sales_rank, publisher, units_sold]
Index: []

In [28]:
dfCleaning.iloc[241,:]

publishing_year                                   NaN
book_name                            Î Î¿Î»Î¹Ï„ÎµÎ¯Î±
author                             Plato, Desmond Lee
language_code                                     eng
author_rating                            Intermediate
book_avarage_rating                               3.9
book_ratings_count                             110274
genre                                   genre fiction
gross_sales                                    387.09
publisher_revenue                             232.254
sale_price                                       0.99
sales_rank                                        265
publisher              Amazon Digital Services,  Inc.
units_sold                                        391
Name: 241, dtype: object

In [29]:
dfCleaning['publishing_year'] = dfCleaning['publishing_year'].astype('Int64')

In [30]:
dfCleaning['publishing_year'].dtype

Int64Dtype()

In [31]:
dfCleaning.sample()

,publishing_year,book_name,author,language_code,author_rating,book_avarage_rating,book_ratings_count,genre,gross_sales,publisher_revenue,sale_price,sales_rank,publisher,units_sold
482,1953,Better Homes & Gardens New Cook Book,Better Homes and Gardens,NaN,Excellent,4.14,93640,nonfiction,165.33,0.0,0.99,534,"Amazon Digital Services, Inc.",4509

In [32]:
# classic < 1800
# early modern 1800 - 1949
# modern 1950 - 1999
# contemprorary > 2000

dfCleaning['publishing_year'] = dfCleaning['publishing_year'].fillna(0)
year = dfCleaning['publishing_year']
dfCleaning['era'] = np.where(year == 0, 'Unknown', np.where(year < 1800, "classic", np.where(year <= 1949, 'Early Modern', np.where(year <= 1999, 'Modern', 'Contemprorary'))))

In [33]:
dfCleaning.insert( 4, 'dialect', dfCleaning['language_code'].copy())

In [34]:
dfCleaning.sample(5)

,publishing_year,book_name,author,language_code,dialect,author_rating,book_avarage_rating,book_ratings_count,genre,gross_sales,publisher_revenue,sale_price,sales_rank,publisher,units_sold,era
759,2004,Messenger,Lois Lowry,eng,eng,Intermediate,3.90,79746,genre fiction,462.84,277.704,3.99,877,"Amazon Digital Services, Inc.",30888,Contemprorary
791,1968,The Last Unicorn,Peter S. Beagle,eng,eng,Excellent,4.18,76277,genre fiction,343.85,0.000,2.99,916,"Amazon Digital Services, Inc.",2916,Modern
825,2008,The Painted Man,Peter V. Brett,eng,eng,Excellent,4.27,64416,genre fiction,454.86,272.916,3.99,966,"Amazon Digital Services, Inc.",2889,Contemprorary
1014,1928,The House at Pooh Corner,"A.A. Milne, Ernest H. Shepard",en-US,en-US,Excellent,4.36,69102,genre fiction,214.92,0.000,1.99,1199,"Amazon Digital Services, Inc.",108,Early Modern
661,2011,Between Shades of Gray,Ruta Sepetys,eng,eng,Excellent,4.36,87718,genre fiction,236.81,142.086,1.99,761,"Amazon Digital Services, Inc.",40176,Contemprorary

In [35]:
dfCleaning['language_code'].unique()

<StringArray>
['en-US', 'eng', nan, 'spa', 'en-GB', 'fre', 'en-CA', 'nl', 'ara']
Length: 9, dtype: str

In [36]:
dfCleaning.loc[
    (dfCleaning['language_code'] == 'en-US') | 
    (dfCleaning['language_code'] == 'en-GB') |
    (dfCleaning['language_code'] == 'en-CA') |
    (dfCleaning['language_code'] == 'eng'),
    'language_code'
    ] = 'English'

dfCleaning.loc[dfCleaning['language_code'] == 'spa', 'language_code'] = 'Spanish'
dfCleaning.loc[dfCleaning['language_code'] == 'fre', 'language_code'] = 'French'
dfCleaning.loc[dfCleaning['language_code'] == 'nl', 'language_code'] = 'Dutch'
dfCleaning.loc[dfCleaning['language_code'] == 'ara', 'language_code'] = 'Arabic'
dfCleaning['language_code'] = dfCleaning['language_code'].fillna("Undefined")

In [37]:
dfCleaning['language_code'].unique()

<StringArray>
['English', 'Undefined', 'Spanish', 'French', 'Dutch', 'Arabic']
Length: 6, dtype: str

In [38]:
dfCleaning[dfCleaning['language_code'] == 'French']

,publishing_year,book_name,author,language_code,dialect,author_rating,book_avarage_rating,book_ratings_count,genre,gross_sales,publisher_revenue,sale_price,sales_rank,publisher,units_sold,era
47,1983,Christine,"Stephen King, Marie Milpois",French,fre,Intermediate,3.72,151160,nonfiction,1766.16,1059.696,0.99,49,"Amazon Digital Services, Inc.",1784,Modern
257,1993,Trainspotting,"Irvine Welsh, Eric Lindor Fall",French,fre,Intermediate,4.07,59453,genre fiction,1100.32,660.192,2.99,279,Random House LLC,368,Modern
287,2001,Dreamcatcher,"Stephen King, William Olivier Desmond",French,fre,Intermediate,3.59,115855,genre fiction,1576.84,0.000,4.99,310,"Amazon Digital Services, Inc.",316,Contemprorary
544,1992,Dolores Claiborne,"Stephen King, Dominique Dill",French,fre,Intermediate,3.81,71053,genre fiction,661.38,396.828,4.38,608,"Amazon Digital Services, Inc.",4077,Modern

In [39]:
dfCleaning.loc[dfCleaning['dialect'] == 'en-US', 'dialect'] = 'US'
dfCleaning.loc[dfCleaning['dialect'] == 'en-GB', 'dialect'] = 'UK'
dfCleaning.loc[dfCleaning['dialect'] == 'en-CA', 'dialect'] = 'Canada'
dfCleaning.loc[dfCleaning['dialect'] == 'eng', 'dialect'] = 'General'

In [40]:
dfCleaning.sample()

,publishing_year,book_name,author,language_code,dialect,author_rating,book_avarage_rating,book_ratings_count,genre,gross_sales,publisher_revenue,sale_price,sales_rank,publisher,units_sold,era
337,1945,Pippi LÃ¥ngstrump,"Astrid Lindgren, Lauren Child, Florence Lambor...",English,General,Excellent,4.11,123065,genre fiction,977.55,586.53,3.99,360,"Amazon Digital Services, Inc.",245,Early Modern

In [41]:
dialect = dfCleaning.loc[dfCleaning['language_code'] == 'English', [ 'language_code', 'dialect']]

In [42]:
dfCleaning.iloc[73:76,:]

,publishing_year,book_name,author,language_code,dialect,author_rating,book_avarage_rating,book_ratings_count,genre,gross_sales,publisher_revenue,sale_price,sales_rank,publisher,units_sold,era
73,1993,"Girl, Interrupted",Susanna Kaysen,English,General,Intermediate,3.90,145161,genre fiction,2724.31,1634.586,1.99,76,Hachette Book Group,1369,Modern
74,2007,"Are You There, Vodka? It's Me, Chelsea",Chelsea Handler,Undefined,NaN,Intermediate,3.85,127096,genre fiction,5462.31,3277.386,3.99,76,Hachette Book Group,1369,Contemprorary
75,1970,Jonathan Livingston Seagull,"Richard Bach, Russell Munson",English,US,Intermediate,3.80,133728,genre fiction,6751.47,0.000,4.99,77,"Amazon Digital Services, Inc.",1353,Modern

In [43]:
dialect.iloc[70:73,:]

   language_code  dialect
73       English  General
75       English       US
76       English  General

In [44]:
dfCleaning.drop('dialect',axis=1, inplace=True)

In [45]:
dfCleaning['publisher'].unique()

<StringArray>
[            'HarperCollins Publishers',
       'Amazon Digital Services,  Inc.',
                  'Hachette Book Group',
              'Penguin Group (USA) LLC',
                     'Random House LLC',
 'Simon and Schuster Digital Sales Inc',
                            'Macmillan',
             'HarperCollins Publishing',
   'HarperCollins Christian Publishing']
Length: 9, dtype: str

In [46]:
dfCleaning['publisher'] = dfCleaning['publisher'].replace({
    'HarperCollins Publishers':'HarperCollins',
    'HarperCollins Christian Publishing':'HarperCollins',
    'HarperCollins Publishing':'HarperCollins'
})

In [47]:
dfCleaning['publisher'].unique()

<StringArray>
[                       'HarperCollins',
       'Amazon Digital Services,  Inc.',
                  'Hachette Book Group',
              'Penguin Group (USA) LLC',
                     'Random House LLC',
 'Simon and Schuster Digital Sales Inc',
                            'Macmillan']
Length: 7, dtype: str

In [48]:
df[df.duplicated(keep='first') == True]

Empty DataFrame
Columns: [index, Publishing Year, Book Name, Author, language_code, Author_Rating, Book_average_rating, Book_ratings_count, genre, gross sales, publisher revenue, sale price, sales rank, Publisher , units sold]
Index: []

there no dublicates after cleaning

Analys

In [49]:
dfCleaning.info()

<class 'pandas.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   publishing_year      1070 non-null   Int64
 1   book_name            1047 non-null   str
 2   author               1070 non-null   str
 3   language_code        1070 non-null   str
 4   author_rating        1070 non-null   str
 5   book_avarage_rating  1070 non-null   float64
 6   book_ratings_count   1070 non-null   int64
 7   genre                1070 non-null   str
 8   gross_sales          1070 non-null   float64
 9   publisher_revenue    1070 non-null   float64
 10  sale_price           1070 non-null   float64
 11  sales_rank           1070 non-null   int64
 12  publisher            1070 non-null   str
 13  units_sold           1070 non-null   int64
 14  era                  1070 non-null   str
dtypes: Int64(1), float64(4), int64(3), str(7)
memory usage: 126.6 KB

In [50]:
dfCleaning.sort_values(by='gross_sales', ascending=False).head()

,publishing_year,book_name,author,language_code,author_rating,book_avarage_rating,book_ratings_count,genre,gross_sales,publisher_revenue,sale_price,sales_rank,publisher,units_sold,era
2,2015,Go Set a Watchman,Harper Lee,English,Novice,3.31,138669,genre fiction,47795.00,28677.000,8.69,3,"Amazon Digital Services, Inc.",5500,Contemprorary
3,2008,When You Are Engulfed in Flames,David Sedaris,English,Intermediate,4.04,150898,fiction,41250.00,24750.000,7.50,3,Hachette Book Group,5500,Contemprorary
4,2011,Daughter of Smoke & Bone,Laini Taylor,English,Intermediate,4.04,198283,genre fiction,37952.50,22771.500,7.99,4,Penguin Group (USA) LLC,4750,Contemprorary
0,1975,Beowulf,"Unknown, Seamus Heaney",English,Novice,3.42,155903,genre fiction,34160.00,20496.000,4.88,1,HarperCollins,7000,Modern
6,2011,The Power of Habit,Charles Duhigg,English,Intermediate,4.03,155977,genre fiction,27491.67,16495.002,6.99,6,HarperCollins,3933,Contemprorary

In [51]:
dfCleaning.groupby('genre')['gross_sales'].mean().sort_values(ascending=False)

genre
genre fiction    1974.080693
fiction          1965.018226
nonfiction       1334.262398
children          926.814667
Name: gross_sales, dtype: float64

In [52]:
dfCleaning.groupby('genre')['units_sold'].sum().sort_values(ascending=False)

genre
genre fiction    7875834
nonfiction       1634759
fiction           545658
children          298118
Name: units_sold, dtype: int64

In [53]:
dfCleaning.groupby('genre')['units_sold'].count().sort_values(ascending=False)

genre
genre fiction    822
nonfiction       171
fiction           62
children          15
Name: units_sold, dtype: int64

In [54]:
dfCleaning.groupby('genre')['sale_price'].mean().sort_values(ascending=False)

genre
children         6.126667
nonfiction       5.462456
fiction          5.216774
genre fiction    4.697092
Name: sale_price, dtype: float64

fiction category contribute in higher average gross sales comparing with nonfiction while it clearly has lower available books  
this might indocates stronger avarage performance

In [55]:
dfCleaning.groupby('author_rating')['gross_sales'].mean().sort_values(ascending=False)

author_rating
Novice          3806.005000
Intermediate    2451.676912
Famous          1145.448302
Excellent        771.822017
Name: gross_sales, dtype: float64

In [56]:
dfCleaning.groupby('author_rating')['units_sold'].count().sort_values(ascending=False)

author_rating
Intermediate    625
Excellent       362
Famous           53
Novice           30
Name: units_sold, dtype: int64

In [57]:
dfCleaning.groupby('author_rating')['units_sold'].sum().sort_values(ascending=False)

author_rating
Intermediate    4963160
Excellent       4828717
Famous           349796
Novice           212696
Name: units_sold, dtype: int64

In [58]:
dfCleaning.groupby('author_rating')['sale_price'].mean().sort_values(ascending=False)

author_rating
Novice          5.648667
Excellent       5.264669
Intermediate    4.665680
Famous          4.134151
Name: sale_price, dtype: float64

although Novice rating category has fewer available books and higher price, but it contribute higher average gross sales  
which may suggest an opportunity in this category

In [59]:
dfCleaning['language_code'].value_counts().sort_values(ascending=False)

language_code
English      1008
Undefined      53
French          4
Spanish         2
Arabic          2
Dutch           1
Name: count, dtype: int64

In [60]:
dialect['dialect'].value_counts().sort_values(ascending=False)

dialect
General    737
US         234
UK          30
Canada       7
Name: count, dtype: int64

English language dominate the data   
which influence weak meaningful analysis across languages of dialects

In [61]:
dfCleaning.groupby('era')['gross_sales'].mean().sort_values(ascending=False)

era
classic          2584.850000
Early Modern     2252.608000
Modern           1975.043889
Contemprorary    1718.131841
Unknown           708.735714
Name: gross_sales, dtype: float64

In [62]:
dfCleaning.groupby('era')['units_sold'].sum().sort_values(ascending=False)

era
Contemprorary    6042528
Modern           3157511
Early Modern      994499
Unknown            95064
classic            64767
Name: units_sold, dtype: int64

In [63]:
dfCleaning.groupby('era')['units_sold'].count().sort_values(ascending=False)

era
Contemprorary    603
Modern           342
Early Modern     105
classic           13
Unknown            7
Name: units_sold, dtype: int64

In [64]:
dfCleaning.groupby('era')['sale_price'].mean().sort_values(ascending=False)

era
Early Modern     5.277619
Contemprorary    4.887446
Modern           4.774035
classic          4.069231
Unknown          3.361429
Name: sale_price, dtype: float64

Early Modern category has lower availiblity but contribute strongly to average gross sales  
i suggest to increase the promotion or republishing for this category

In [65]:
dfCleaning.to_csv('../data/cleaned_books_sales.csv', index=False)